filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            equals:
              docker.container.name: mcod-redis
          config:
            - module: redis
              log:
                input:
                  type: docker
                  combine_partial: true
                  containers:
                    path: "/usr/share/filebeat/containers"
                    stream: "stdout"
                  containers.ids:
                    - "${data.docker.container.id}"
                  exclude_lines: ["^\\s+[\\-`('.|_]"]
              slowlog:
                var.hosts: ["mcod-redis:6379"]
        - condition:
            equals:
              docker.container.name: mcod-nginx
          config:
            - module: nginx
              access:
                enabled: true
                input:
                  type: docker
                  combine_partial: true
                  containers:
                    path: "/usr/share/filebeat/containers"
                    stream: "stdout"
                  containers.ids:
                    - "${data.docker.container.id}"
              error:
                enabled: true
                input:
                  type: docker
                  combine_partial: true
                  containers:
                    path: "/usr/share/filebeat/containers"
                    stream: "stderr"
                  containers.ids:
                    - "${data.docker.container.id}"
        - condition:
            equals:
              docker.container.name: mcod-db
          config:
            - module: postgresql
              log:
                input:
                  type: docker
                  combine_partial: true
                  containers:
                    path: "/usr/share/filebeat/containers"
                    stream: "all"
                  containers.ids:
                    - "${data.docker.container.id}"
        - condition:
            regexp:
              docker.container.name: mcod-elasticsearch-*
          config:
            - module: elasticsearch
              server:
                input:
                  type: docker
                  combine_partial: true
                  containers:
                    path: "/usr/share/filebeat/containers"
                    stream: "all"
                  containers.ids:
                    - "${data.docker.container.id}"

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "mcod-kibana:5601"

output.elasticsearch:
  hosts: ["mcod-monitoring:9200"]

logging.to_files: true
logging.to_syslog: false
