---
- name: install java
  dnf: name=java-1.8.0-openjdk.x86_64 state=installed
  become: true

- name: install kibana 6.2.4
  become: yes
  dnf:
    name: https://artifacts.elastic.co/downloads/kibana/kibana-6.2.4-x86_64.rpm
    state: installed

- name: enable and reload kibana server
  service: name=kibana enabled=yes state=restarted
  become: true

- name: restart kibana server
  service: name=kibana enabled=yes state=restarted
  become: true
