- type: http
  schedule: '@every 60s'
  name: 'api'
  urls:
    - "${API_URL}/stats"
    - "${API_URL}/applications"
    - "${API_URL}/articles"
    - "${API_URL}/institutions"
    - "${API_URL}/datasets"
    - "${API_URL}/resources"
  check.request:
    method: GET
    headers:
      'User-Agent': 'mcod-heartbeat'
  check.response.status: 200
  check.response.json:
    - description: results count greater then 0
      condition:
        range:
          meta.count:
            gt: 0

- type: http
  name: 'admin'
  schedule: '@every 60s'
  urls:
    - "${ADMIN_URL}"
  check.request:
    method: GET
    headers:
      'User-Agent': 'mcod-heartbeat'
  check.response.status: 200

- type: http
  schedule: '@every 360s'
  name: 'docs'
  urls:
    - "${API_URL}/doc"
    - "${API_URL}/spec/1.4"
  check.request:
    method: GET
    headers:
      'User-Agent': 'mcod-heartbeat'
  check.response.status: 200
