---
- name: install java
  dnf: name=java-1.8.0-openjdk.x86_64 state=present
  become: true

- name: install elasticsearch 6.2.4
  become: yes
  dnf:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.rpm
    state: present

- name: copy stopwords.txt
  become: yes
  command: cp -f /vagrant/docker/elasticsearch/stopwords.txt /etc/elasticsearch

- name: copy hunspell config files
  become: yes
  command: cp -rf /vagrant/docker/elasticsearch/hunspell /etc/elasticsearch

- name: enable and reload elasticsearch server
  service: name=elasticsearch enabled=yes state=restarted
  become: true

- name: install analysis-stempel plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin -s install analysis-stempel
  become: true
  ignore_errors: true

- name: install analysis-icu plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin -s install analysis-icu
  become: true
  ignore_errors: true

- name: restart elasticsearch server
  service: name=elasticsearch enabled=yes state=restarted
  become: true
