- name: install frontend dependencies
  command: npm install
  args:
    chdir: /vagrant/frontend
  become: no

- name: generate local-proxy.conf.json
  template:
    src: templates/mcod/local-proxy.conf.json.j2
    dest: /vagrant/frontend/local-proxy.conf.json
    owner: vagrant
    group: vagrant
    mode: 0644
    force: no

- name: run create-env.sh
  command: bash create-env.sh
  args:
    chdir: /vagrant/frontend
  become: no